# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b406a5a2d61555203dc3f7dcc01094030445c7b71e8ce3260ebf19e8f9cfd913b354c50bc0c72425d9fd88912cdfb19da1ddba737b3e718fcf86276c600d5df4
  facebook_app_id: ENV['FB_APP_ID']
  facebook_app_secret: ENV['FB_APP_SECRET']
  
test:
  secret_key_base: ea265d631024a4aaf549aedc56afd49b9d9ca39a3911166b8f1f5512f9a40b3076197bc772441f38feddce69f2938427a451c5d520ba8002f1b00577dd0da0ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: ENV['FB_APP_ID']
  facebook_app_secret: ENV['FB_APP_SECRET']
